version: "2"

services:
  
  backend:
    build: backend
    ports:
    - "5001:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        
  webui:
    build: webui
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201

  redis:
    image: redis
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
