version: "2"

services:
  backend:
    build: backend
    ports:
    - "8001:80"

  webui:
    build: webui
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"

  redis:
    image: redis
