version: "2"

services:
  backend:
    build: backend
    ports:
    - "5001:80"
    
  webui:
    build: webui
    ports:
    - "5000:80"
    volumes:
    - "./webui/files/:/files/"

  redis:
    image: redis
