apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image:  DOCKER_REGISTRY/backend:BUILD_NUMBER
        ports:
          - name: http-port
            containerPort: 80
